---
sidebar: sidebar 
permalink: reference-azure-backup-tiers.html 
keywords: microsoft azure, azure, cool, access tier, archive 
summary: Cloud Backup은 하나의 Azure 아카이브 액세스 계층 및 대부분의 영역을 지원합니다. 
---
= Azure 아카이브 계층 및 복원 검색 시간
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup은 하나의 Azure 아카이브 액세스 계층 및 대부분의 영역을 지원합니다.



== Cloud Backup에 지원되는 Azure Blob 액세스 계층

백업 파일이 처음 생성될 때는 _Cool_access 계층에 저장됩니다. 이 계층은 자주 액세스하지 않는 데이터를 저장하는 데 최적화되어 있지만 필요할 때 즉시 액세스할 수 있습니다.

소스 클러스터에서 ONTAP 9.10.1 이상이 실행 중인 경우 추가 비용 최적화를 위해 일정 일(일반적으로 30일 이상) 후에 _Cool_to_Azure Archive_storage에서 백업을 계층화하도록 선택할 수 있습니다. 이 계층의 데이터는 필요할 때 즉시 액세스할 수 없으며 검색 비용을 더 높여야 하기 때문에 이러한 아카이브 백업 파일에서 데이터를 복원해야 하는 빈도를 고려해야 합니다. 에 대한 다음 섹션을 참조하십시오 <<Restoring data from archival storage,아카이브 스토리지에서 데이터 복원>>.

이러한 유형의 수명 주기 규칙으로 Cloud Backup을 구성할 때는 Azure 계정에서 컨테이너를 설정할 때 수명 주기 규칙을 구성하지 않아야 합니다.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["Azure Blob 액세스 계층에 대해 알아보십시오"^].



== 아카이브 스토리지에서 데이터 복원

오래된 백업 파일을 아카이브 스토리지에 저장하는 것은 Cool 스토리지보다 훨씬 저렴하지만, 복원 작업을 위해 Azure Archive의 백업 파일에서 데이터에 액세스하는 데 더 많은 시간이 걸리고 비용이 더 많이 듭니다.

Azure Archive에서 데이터를 복원하는 데 비용이 얼마나 드는가?:: Azure Archive에서 데이터를 검색할 때 선택할 수 있는 두 가지 복원 우선 순위가 있습니다.
+
--
* * 높음 *: 가장 빠른 검색, 높은 비용
* * 표준 *: 검색 속도 감소, 비용 절감


각 방법은 GB당 검색 비용과 요청당 수수료를 다르게 합니다. Azure 지역별 Azure Archive에 대한 자세한 가격을 보려면 를 방문하십시오 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["Azure 가격 책정 페이지입니다"].

--
Azure Archive에 보관된 데이터를 복원하는 데 시간이 얼마나 걸립니까?:: 복원 시간을 구성하는 두 가지 부분이 있습니다.
+
--
* * 검색 시간 *: Azure Archive에서 보관된 백업 파일을 검색하여 Cool storage에 저장하는 시간입니다. 이를 "재수화" 시간이라고도 합니다. 검색 시간은 선택한 복원 우선 순위에 따라 다릅니다.
+
** * 높음 *: 1시간 미만
** * 표준 *: 15시간 미만


* * 복원 시간 *: Cool storage의 백업 파일에서 데이터를 복원하는 시간입니다. 이 시간은 보관 계층을 사용하지 않을 때 Cool 스토리지에서 직접 수행하는 일반적인 복원 작업과 다르지 않습니다.


Azure Archive 검색 옵션에 대한 자세한 내용은 을 참조하십시오 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/#faq["이 Azure FAQ를 참조하십시오"].

--

