---
sidebar: sidebar 
permalink: reference-aws-backup-tiers.html 
keywords: aws, amazon, s3, storage classes, archive 
summary: Cloud Backup은 2개의 S3 아카이브 스토리지 클래스와 대부분의 영역을 지원합니다. 
---
= AWS S3 아카이브 스토리지 클래스 및 복원 검색 시간
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup은 2개의 S3 아카이브 스토리지 클래스와 대부분의 영역을 지원합니다.



== Cloud Backup에 지원되는 S3 아카이브 스토리지 클래스

백업 파일이 처음 생성되면 S3_Standard_Storage에 저장됩니다. 이 계층은 자주 액세스하지 않는 데이터를 저장하는 데 최적화되어 있지만 이를 즉시 액세스할 수도 있습니다. 30일 후에 백업이 S3_Standard - Infrequent Access_storage 클래스로 전환되어 비용이 절감됩니다.

소스 클러스터에서 ONTAP 9.10.1 이상이 실행 중인 경우 추가 비용 최적화를 위해 일정 일(일반적으로 30일 이상) 후에 백업을 _S3 Glacier_또는 _S3 Glacier Deep Archive_storage로 계층화하도록 선택할 수 있습니다. 이러한 계층의 데이터는 필요할 때 즉시 액세스할 수 없으며 검색 비용을 더 높여야 하기 때문에 이러한 아카이브 백업 파일에서 데이터를 복원해야 하는 빈도를 고려해야 합니다. 에 대한 섹션을 참조하십시오 <<Restoring data from archival storage,아카이브 스토리지에서 데이터 복원>>.

이러한 유형의 수명주기 규칙을 사용하여 Cloud Backup을 구성할 때는 AWS 계정에서 버킷을 설정할 때 수명주기 규칙을 구성하지 않아야 합니다.

https://aws.amazon.com/s3/storage-classes/["S3 스토리지 클래스에 대해 알아보십시오"^].



== 아카이브 스토리지에서 데이터 복원

오래된 백업 파일을 아카이브 스토리지에 저장하는 것은 Standard 또는 Standard-IA 스토리지에 비해 훨씬 저렴하지만, 복원 작업을 위해 아카이브 스토리지에 있는 백업 파일의 데이터에 액세스하는 데 시간이 더 오래 걸리고 비용이 더 많이 듭니다.

Amazon S3 Glacier 및 Amazon S3 Glacier Deep Archive에서 데이터를 복원하는 데 비용이 얼마나 드나요?:: Amazon S3 Glacier에서 데이터를 검색할 때 3가지 복원 우선순위를 선택할 수 있으며, Amazon S3 Glacier Deep Archive에서 데이터를 검색할 경우 2가지 복원 우선순위를 선택할 수 있습니다. S3 Glacier Deep Archive 비용 미만 S3 Glacier:
+
--
[cols="25,25,25,25"]
|===
| 아카이브 계층 3+| 복구 우선 순위 및 비용 


|  | * 높음 * | * 표준 * | * 낮음 * 


| * S3 빙하 * | 신속한 검색, 높은 비용 | 검색 속도 감소, 비용 절감 | 가장 느린 검색, 가장 낮은 비용 


| * S3 Glacier Deep Archive * |  | 빠른 검색, 높은 비용 | 검색 속도 감소, 비용 최소화 
|===
각 방법은 GB당 검색 비용과 요청당 수수료를 다르게 합니다. AWS 지역별 S3 Glacier 가격 에 대한 자세한 내용은 를 참조하십시오 https://aws.amazon.com/s3/pricing/["Amazon S3 가격 페이지"^].

--
Amazon S3 Glacier에 보관된 개체를 복원하는 데 시간이 얼마나 걸립니까?:: 총 복원 시간을 구성하는 두 가지 부분이 있습니다.
+
--
* * 검색 시간 *: 아카이브에서 백업 파일을 검색하여 표준 저장소에 저장하는 시간입니다. 이를 "재수화" 시간이라고도 합니다. 검색 시간은 선택한 복원 우선 순위에 따라 다릅니다.
+
[cols="25,20,20,20"]
|===
| 아카이브 계층 3+| 복구 우선 순위 및 검색 시간 


|  | * 높음 * | * 표준 * | * 낮음 * 


| * S3 빙하 * | 3-5분 | 3-5시간 | 5-12시간 


| * S3 Glacier Deep Archive * |  | 12시간 | 48시간 
|===
* * 복원 시간 *: 표준 저장소의 백업 파일에서 데이터를 복원하는 시간입니다. 이 시간은 아카이브 계층을 사용하지 않을 때 표준 스토리지에서 직접 수행하는 일반적인 복원 작업과 다르지 않습니다.


Amazon S3 Glacier 및 S3 Glacier Deep Archive 검색 옵션에 대한 자세한 내용은 을 참조하십시오 https://aws.amazon.com/s3/faqs/#Amazon_S3_Glacier["이러한 스토리지 클래스에 대한 Amazon FAQ가 있습니다"^].

--

