---
sidebar: sidebar 
permalink: task-restore-oracle-data.html 
keywords: restore, Azure, Amazon Web services, Oracle database 
summary: 클라우드에서 사내 SnapCenter 서버로 Oracle 데이터베이스를 복원할 수 있습니다. 
---
= Oracle 데이터베이스를 복원합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Oracle 데이터베이스는 동일한 SnapCenter 서버 호스트, 동일한 SVM 또는 동일한 데이터베이스 호스트에만 복원할 수 있습니다. RAC 데이터베이스의 경우 백업이 생성된 사내 노드에 데이터가 복구됩니다.

제어 파일 복원이 있는 전체 데이터베이스만 지원됩니다. 아카이브 로그가 AFS에 없는 경우 복구에 필요한 아카이브 로그가 포함된 위치를 지정해야 합니다.

* 단계 *

. Cloud Manager UI에서 * 백업 및 복원 * > * 응용 프로그램 * 을 클릭합니다.
. 필터 기준 * 필드에서 필터 * 유형 * 을 선택하고 드롭다운에서 * Oracle * 을 선택합니다.
. 복원하려는 데이터베이스에 해당하는 * View Details * 를 클릭하고 * Restore * 를 클릭합니다.
. 복원 유형 페이지에서 다음 작업을 수행합니다.
+
.. 전체 데이터베이스와 함께 제어 파일을 복원하려면 * 제어 파일 * 을 선택합니다.
.. 복원 및 복구에 필요한 경우 * 데이터베이스 상태 변경 * 을 선택하여 복원 및 복구 작업을 수행하는 데 필요한 상태로 데이터베이스의 상태를 변경합니다.
+
상위 데이터베이스에서 하위 데이터베이스까지의 다양한 상태는 열기, 마운트, 시작 및 종료입니다. 데이터베이스가 더 높은 상태에 있지만 복원 작업을 수행하려면 상태를 더 낮은 상태로 변경해야 하는 경우 이 확인란을 선택해야 합니다. 데이터베이스가 더 낮은 상태에 있지만 복원 작업을 수행하려면 상태를 더 높은 상태로 변경해야 하는 경우 확인란을 선택하지 않아도 데이터베이스 상태가 자동으로 변경됩니다.

+
데이터베이스가 열려 있는 상태이고 복구를 위해 데이터베이스가 마운트된 상태여야 하는 경우 이 확인란을 선택한 경우에만 데이터베이스 상태가 변경됩니다.



. 복구 범위 페이지에서 다음 작업을 수행합니다.
+
.. 복구 범위를 지정합니다.
+
|===
| 만약... | 수행할 작업... 


 a| 
마지막 트랜잭션으로 복구하려고 합니다
 a| 
모든 로그 * 를 선택합니다.



 a| 
특정 SCN(시스템 변경 번호)으로 복구하려는 경우
 a| 
SCN(시스템 변경 번호) * 까지 * 를 선택합니다.



 a| 
특정 데이터 및 시간으로 복구하려는 경우
 a| 
날짜 및 시간 * 을 선택합니다.

데이터베이스 호스트의 표준 시간대의 날짜 및 시간을 지정해야 합니다.



 a| 
복구하기를 원하지 않습니다
 a| 
No recovery * 를 선택합니다.



 a| 
외부 아카이브 로그 위치를 지정하려는 경우
 a| 
아카이브 로그가 AFS에 없는 경우 복구에 필요한 아카이브 로그가 포함된 위치를 지정해야 합니다.

|===
.. 복구 후 데이터베이스를 열려면 이 확인란을 선택합니다.
+
RAC 설정에서는 복구에 사용되는 RAC 인스턴스만 복구 후 열립니다.



. 세부 정보를 검토하고 * Restore * 를 클릭합니다.

