---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: SQL Server 데이터베이스를 클라우드에서 사내 SnapCenter 서버로 복원할 수 있습니다. 
---
= SQL Server 데이터베이스를 복원합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
SQL Server 데이터베이스를 동일한 호스트 또는 대체 호스트로 복원할 수 있습니다. 로그 백업 복구 및 가용성 그룹의 재시딩은 지원되지 않습니다.

* 단계 *

. Cloud Manager UI에서 * 백업 및 복원 * > * 응용 프로그램 * 을 클릭합니다.
. 필터 기준 * 필드에서 필터 * 유형 * 을 선택하고 드롭다운에서 * SQL * 을 선택합니다.
. 사용 가능한 모든 백업을 보려면 * 세부 정보 보기 * 를 클릭합니다.
. 백업을 선택하고 * 복원 * 을 클릭합니다.
. 데이터베이스 파일을 복원할 위치를 선택합니다.
+
|===
| 옵션을 선택합니다 | 설명 


 a| 
백업을 생성한 동일한 호스트에 데이터베이스를 복구합니다
 a| 
백업을 수행한 동일한 SQL Server에 데이터베이스를 복원하려면 이 옵션을 선택합니다.



 a| 
데이터베이스를 대체 호스트로 복구합니다
 a| 
백업을 수행하는 동일한 호스트 또는 다른 호스트에 있는 다른 SQL Server로 데이터베이스를 복구하려는 경우 이 옵션을 선택합니다.

호스트 이름을 선택하고 데이터베이스 이름(선택 사항)을 입력한 다음 인스턴스를 선택하고 복구 경로를 지정합니다.


NOTE: 대체 경로에 제공된 파일 확장자는 원본 데이터베이스 파일의 파일 확장명과 동일해야 합니다.

Restore Scope 페이지에 * Restore the database to an alternate host * 옵션이 표시되지 않으면 브라우저 캐시를 지웁니다.

|===
. 사전 복원 옵션 * 페이지에서 다음 옵션 중 하나를 선택합니다.
+
** 같은 이름으로 데이터베이스를 복원하려면 * 복원 중에 같은 이름으로 데이터베이스 덮어쓰기 * 를 선택합니다.
** 데이터베이스를 복원하고 기존 복제 설정을 유지하려면 * SQL 데이터베이스 복제 설정 유지 * 를 선택합니다.


. 사후 복원 옵션 * 페이지에서 추가 트랜잭션 로그를 복원하기 위한 데이터베이스 상태를 지정하려면 다음 옵션 중 하나를 선택합니다.
+
** 지금 필요한 모든 백업을 복원하는 경우 * 작동 가능하나 * 를 선택합니다.
+
이는 기본 동작으로, 커밋되지 않은 트랜잭션을 롤백하여 데이터베이스를 사용할 수 있도록 합니다. 백업을 생성할 때까지 추가 트랜잭션 로그를 복원할 수 없습니다.

** 커밋되지 않은 트랜잭션을 롤백하지 않고 데이터베이스를 비작동 상태로 두려면 * 비작동, 사용 가능 * 을 선택합니다.
+
추가 트랜잭션 로그를 복원할 수 있습니다. 데이터베이스가 복구될 때까지 데이터베이스를 사용할 수 없습니다.

** 데이터베이스를 읽기 전용 모드로 전환하려면 * 읽기 전용 모드 및 사용 가능 * 을 선택합니다.
+
이 옵션은 커밋되지 않은 트랜잭션을 수행하지 않지만 복구 효과를 되돌릴 수 있도록 실행 취소된 작업을 대기 파일에 저장합니다.

+
Undo directory(디렉터리 실행 취소) 옵션이 활성화된 경우 더 많은 트랜잭션 로그가 복원됩니다. 트랜잭션 로그의 복원 작업이 실패한 경우 변경 내용을 롤백할 수 있습니다. 자세한 내용은 SQL Server 설명서를 참조하십시오.



. 세부 정보를 검토하고 * Restore * 를 클릭합니다.

