---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore' 
summary: Cloud Backup의 새로운 기능에 대해 알아보십시오. 
---
= 클라우드 백업의 새로운 기능
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Backup의 새로운 기능에 대해 알아보십시오.



== 2022년 4월 4일



=== SnapCenter에 기반을 둔 애플리케이션 클라우드 백업 1.1.0 이 현재 GA입니다

새로운 Cloud Backup for Applications 기능을 사용하면 Oracle 및 Microsoft SQL에 대한 기존 애플리케이션 정합성 보장 스냅샷(백업)을 사내 운영 스토리지에서 AWS S3 또는 Azure Blob의 클라우드 오브젝트 스토리지로 오프로드할 수 있습니다.

필요한 경우 클라우드에서 사내로 데이터를 복원할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-protect-app-data-to-cloud.html["사내 애플리케이션 데이터를 클라우드로 보호하는 방법에 대해 자세히 알아보십시오"].



=== 모든 ONTAP 백업 파일에서 볼륨 또는 파일을 검색하는 새로운 검색 및 복원 기능

이제 일부 또는 전체 볼륨 이름, 일부 또는 전체 파일 이름, 크기 범위 및 추가 검색 필터를 통해 * 모든 ONTAP 백업 파일 * 에서 볼륨 또는 파일을 검색할 수 있습니다. 이 방법은 어떤 클러스터나 볼륨이 데이터의 소스인지 잘 모르면 복원하려는 데이터를 찾을 수 있는 새로운 방법입니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["검색 및 amp;Restore 사용 방법에 대해 알아봅니다"].



== 2022년 3월 3일



=== GKE Kubernetes 클러스터에서 Google Cloud 스토리지로 영구 볼륨을 백업하는 기능

GKE 클러스터에 NetApp Astra Trident가 설치되어 있고 Cloud Volumes ONTAP for GCP를 클러스터의 백엔드 스토리지로 사용하는 경우, Google Cloud 스토리지와 영구 볼륨을 백업 및 복원할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-backup-kubernetes-to-gcp.html["자세한 내용을 보려면 여기를 클릭하십시오"].



=== Cloud Data Sense를 사용하여 Cloud Backup 파일을 검사하는 베타 기능은 이 릴리즈에서 더 이상 제공되지 않습니다



== 2022년 2월 14일



=== 이제 단일 클러스터의 개별 볼륨에 백업 정책을 할당할 수 있습니다

과거에는 클러스터의 모든 볼륨에 단일 백업 정책만 할당할 수 있었습니다. 이제 단일 클러스터에 대해 여러 백업 정책을 생성하고 여러 볼륨에 서로 다른 정책을 적용할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-manage-backups-ontap#changing-the-policy-assigned-to-existing-volumes["클러스터에 대한 새 백업 정책을 생성하고 이를 선택한 볼륨에 할당하는 방법을 알아보십시오"].



=== 새 옵션을 사용하면 새로 생성된 볼륨에 기본 백업 정책을 자동으로 적용할 수 있습니다

과거에는 Cloud Backup을 활성화한 후 작업 환경에서 생성된 새 볼륨을 수동으로 백업 정책을 적용해야 했습니다. 이제 Cloud Manager, System Manager, CLI 또는 API에서 볼륨이 생성되었는지에 관계없이 Cloud Backup은 볼륨을 검색하고 선택한 백업 정책을 기본 정책으로 적용합니다.

이 옵션은 새 작업 환경에서 백업을 설정하거나 기존 작업 환경의 _Manage Volumes_페이지에서 백업을 설정할 때 사용할 수 있습니다.



=== 새 작업 모니터를 사용하여 모든 백업 및 복원 작업의 진행 상태를 확인할 수 있습니다

백업 정책 변경 또는 백업 삭제와 같이 여러 볼륨에 대해 작업을 시작한 경우 작업 모니터를 사용하면 모든 볼륨에서 작업이 완료된 시점을 확인할 수 있습니다. https://docs.netapp.com/us-en/cloud-manager-backup-restore/task-monitor-backup-jobs.html["작업 모니터 사용 방법을 참조하십시오"].



== 2022년 1월 2일



=== AKS Kubernetes 클러스터에서 Azure Blob 스토리지로 영구 볼륨을 백업할 수 있습니다

AKS 클러스터에 NetApp Astra Trident가 설치되어 있고 Azure용 Cloud Volumes ONTAP를 클러스터용 백엔드 스토리지로 사용하는 경우, Azure Blob 스토리지간에 볼륨을 백업 및 복원할 수 있습니다. link:task-backup-kubernetes-to-azure.html["자세한 내용을 보려면 여기를 클릭하십시오"].



=== 업계 표준에 더욱 부합하도록 이번 릴리스에서 Cloud Backup Service 요금이 변경되었습니다

백업 파일의 크기에 따라 NetApp의 용량을 지불하는 대신, 현재 백업 중인 소스 ONTAP 볼륨의 논리적 사용 용량(ONTAP 효율성 이전)을 기준으로 계산한, 보호하는 데이터에 대해서만 비용을 지불하면 됩니다. 이 용량을 FETB(Front-End Terabytes)라고도 합니다.



== 2021년 11월 28일



=== EKS Kubernetes 클러스터에서 Amazon S3로 영구 볼륨을 백업하는 기능

EKS 클러스터에 NetApp Astra Trident가 설치되어 있고 Cloud Volumes ONTAP for AWS를 클러스터의 백엔드 스토리지로 사용하는 경우 Amazon S3로 볼륨을 백업 및 복원할 수 있습니다. link:task-backup-kubernetes-to-s3.html["자세한 내용을 보려면 여기를 클릭하십시오"].



=== DP 볼륨을 백업하는 향상된 기능

Cloud Backup은 이제 SVM-DR 관계의 타겟 ONTAP 시스템에 있는 DP 볼륨의 백업을 생성할 수 있도록 지원합니다. 몇 가지 제한 사항이 있습니다. 을 참조하십시오 link:concept-ontap-backup-to-cloud.html#limitations["제한 사항"] 를 참조하십시오.



== 2021년 11월 5일



=== 온프레미스 ONTAP 시스템으로 볼륨을 복원할 때 개인 엔드포인트를 선택할 수 있습니다

Amazon S3 또는 Azure Blob에 있는 백업 파일에서 온프레미스 ONTAP 시스템으로 볼륨을 복원할 때 온프레미스 시스템에 안전하게 비공개로 연결하는 프라이빗 끝점을 선택할 수 있습니다.



=== 이제 며칠 후 오래된 백업 파일을 아카이브 스토리지에 계층화하여 비용을 절감할 수 있습니다

클러스터에서 ONTAP 9.10.1 이상이 실행 중이고 AWS 또는 Azure 클라우드 스토리지를 사용 중인 경우 백업을 아카이브 스토리지에 계층화할 수 있습니다. 에 대한 자세한 내용을 참조하십시오 link:reference-aws-backup-tiers.html["AWS S3 아카이빙 스토리지 클래스"] 및 link:reference-azure-backup-tiers.html["Azure Blob 아카이브 액세스 계층"].



=== Cloud Backup BYOL 라이센스는 Digital Wallet의 Data Services Licenses 탭으로 이동했습니다

Cloud Backup에 대한 BYOL 라이센스는 Cloud Backup Licenses 탭에서 Cloud Manager Digital Wallet의 Data Services Licenses 탭으로 이동했습니다.



== 2021년 10월 4일



=== 이제 볼륨 또는 파일 복원을 수행할 때 백업 페이지에서 백업 파일 크기를 사용할 수 있습니다

불필요한 대용량 백업 파일을 삭제하거나 백업 파일 크기를 비교하여 악성 소프트웨어 공격으로 인해 발생할 수 있는 비정상적인 백업 파일을 확인할 수 있는 경우에 유용합니다.



=== TCO 계산기를 사용하여 클라우드 백업 비용을 비교할 수 있습니다

총 소유 비용 계산기는 Cloud Backup의 총 소유 비용을 파악하고 이러한 비용을 기존 백업 솔루션과 비교하고 잠재적인 절감 효과를 추정하는 데 도움이 됩니다. 확인해 보십시오https://cloud.netapp.com/cloud-backup-service-tco-calculator["여기"^].



=== 작업 환경의 클라우드 백업 등록을 취소하는 기능입니다

이제 손쉽게 할 수 있습니다 link:task_manage_backups.html#unregistering-cloud-backup-for-a-working-environment["작업 환경의 클라우드 백업 등록을 취소합니다"] 해당 작업 환경에 더 이상 백업 기능을 사용하지 않거나 비용이 청구되지 않는 경우



== 2021년 9월 2일



=== 볼륨의 필요 시 백업을 생성하는 기능입니다

이제 언제든지 주문형 백업을 생성하여 볼륨의 현재 상태를 캡처할 수 있습니다. 이 기능은 볼륨에 중요한 변경 사항이 있고 예약된 다음 백업이 해당 데이터를 보호할 때까지 기다리지 않으려는 경우에 유용합니다.

link:task-manage-backups-ontap.html#creating-a-manual-volume-backup-at-any-time["필요 시 백업을 생성하는 방법을 확인하십시오"].



=== Amazon S3에 대한 보안 백업을 위해 전용 인터페이스 연결을 정의하는 기능

온-프레미스 ONTAP 시스템에서 Amazon S3로 백업을 구성할 때 이제 활성화 마법사에서 전용 인터페이스 끝점에 대한 연결을 정의할 수 있습니다. 이를 통해 사내 시스템을 AWS PrivateLink 기반의 서비스에 안전하게 비공개로 연결하는 네트워크 인터페이스를 사용할 수 있습니다. link:task-backup-onprem-to-aws.html#preparing-amazon-s3-for-backups["이 옵션에 대한 자세한 내용을 참조하십시오"].



=== 이제 데이터를 Amazon S3에 백업할 때 데이터 암호화에 대해 자체 고객 관리 키를 선택할 수 있습니다

추가 보안 및 제어를 위해 기본 Amazon S3 암호화 키를 사용하는 대신 활성화 마법사에서 데이터 암호화에 대해 고객이 관리하는 키를 직접 선택할 수 있습니다. 이 기능은 사내 ONTAP 시스템 또는 AWS의 Cloud Volumes ONTAP 시스템에서 백업을 구성할 때 사용할 수 있습니다.



=== 이제 30,000개 이상의 파일이 있는 디렉토리에서 파일을 복원할 수 있습니다



== 2021년 8월 1일



=== Azure Blob에 대한 보안 백업을 위해 프라이빗 엔드포인트 연결을 정의하는 기능입니다

온프레미스 ONTAP 시스템에서 Azure Blob으로 백업을 구성하는 경우 활성화 마법사에서 Azure 프라이빗 엔드포인트의 연결을 정의할 수 있습니다. 이를 통해 Azure Private Link가 지원되는 서비스에 개인 및 안전하게 연결하는 네트워크 인터페이스를 사용할 수 있습니다.



=== 이제 시간별 백업 정책이 지원됩니다

이 새로운 정책은 기존 일일, 주별 및 월별 정책에 추가됩니다. 시간별 백업 정책은 최소 RPO(복구 시점 목표)를 제공합니다.



== 2021년 7월 7일



=== 이제 다른 계정과 다른 지역을 사용하여 백업을 만들 수 있습니다

이제 Cloud Backup을 사용하면 Cloud Volumes ONTAP 시스템에 사용 중인 계정/가입과 다른 계정/가입을 사용하여 백업을 생성할 수 있습니다. 또한 Cloud Volumes ONTAP 시스템이 배포된 영역과 다른 영역에 백업 파일을 만들 수도 있습니다.

이 기능은 AWS 또는 Azure를 사용하는 경우, 기존 작업 환경에서 백업을 사용하도록 설정할 때만 사용할 수 있으며, 새로운 Cloud Volumes ONTAP 작업 환경을 생성할 때는 사용할 수 없습니다.



=== 이제 데이터를 Azure Blob에 백업할 때 데이터 암호화에 사용할 자체 고객 관리 키를 선택할 수 있습니다

추가 보안 및 제어를 위해 기본 Microsoft 관리 암호화 키를 사용하는 대신 활성화 마법사에서 데이터 암호화에 대해 고객이 관리하는 키를 직접 선택할 수 있습니다. 이 기능은 사내 ONTAP 시스템 또는 Azure의 Cloud Volumes ONTAP 시스템에서 백업을 구성할 때 사용할 수 있습니다.



=== 이제 단일 파일 복원을 사용할 때 한 번에 최대 100개의 파일을 복원할 수 있습니다



== 2021년 6월 7일



=== ONTAP 9.8 이상을 사용할 때 DP 볼륨에 대해 제한 사항이 해제되었습니다

데이터 보호(DP) 볼륨 백업에 대해 알려진 두 가지 제한 사항이 해결되었습니다.

* 이전에는 다중 구간 백업은 SnapMirror 관계 유형이 Mirror-Vault 또는 Vault인 경우에만 작동했습니다. 이제 관계 유형이 MirrorAllSnapshots인 경우 백업을 수행할 수 있습니다.
* 이제 Cloud Backup은 SnapMirror 정책에 구성된 한 백업에 레이블을 사용할 수 있습니다. 매일, 매주 또는 매월 이름이 있는 라벨을 요구하는 제한은 사라졌습니다.




== 2021년 5월 5일



=== 온프레미스 클러스터 데이터를 Google 클라우드 스토리지 또는 NetApp StorageGRID 시스템으로 백업합니다

이제 사내 ONTAP 시스템에서 Google 클라우드 스토리지 또는 NetApp StorageGRID 시스템으로 백업을 생성할 수 있습니다. 을 참조하십시오 link:task-backup-onprem-to-gcp.html["Google Cloud Storage로 백업"^] 및 link:task-backup-onprem-private-cloud.html["StorageGRID에 백업 중입니다"^] 를 참조하십시오.



=== 이제 System Manager를 사용하여 클라우드 백업 작업을 수행할 수 있습니다

ONTAP 9.9.1의 새로운 기능을 사용하면 System Manager를 사용하여 사내 ONTAP 볼륨의 백업을 클라우드 백업을 통해 설정한 오브젝트 스토리지로 전송할 수 있습니다. link:https://docs.netapp.com/us-en/ontap/task_cloud_backup_data_using_cbs.html["System Manager를 사용하여 Cloud Backup을 사용하여 볼륨을 클라우드에 백업하는 방법을 알아보십시오."^]



=== 몇 가지 향상된 기능을 통해 백업 정책이 개선되었습니다

* 이제 일일, 주별 및 월별 백업을 조합하여 사용자 지정 정책을 생성합니다.
* 백업 정책을 변경할 때 변경 사항은 원래 백업 정책을 사용하는 모든 볼륨에 대한 모든 새 백업 * 및 * 에 적용됩니다. 이전에는 새 볼륨 백업에만 변경 사항이 적용되었습니다.




=== 기타 백업 및 복원 기능 향상

* 백업 파일에 대한 클라우드 대상을 구성할 때 이제 Cloud Volumes ONTAP 시스템이 상주하는 지역이 아닌 다른 영역을 선택할 수 있습니다.
* 단일 볼륨에 대해 생성할 수 있는 백업 파일 수가 1,019에서 4,000개로 증가했습니다.
* 단일 볼륨에 대한 모든 백업 파일을 삭제하는 이전 기능 외에도 볼륨에 대해 하나의 백업 파일만 삭제하거나, 필요한 경우 전체 작업 환경에 대한 모든 백업 파일을 삭제할 수 있습니다.

